a

diff --git a/.github/workflows/build-and-deploy-alpha-release.yml b/.github/workflows/build-and-deploy-alpha-release.yml
--- a/.github/workflows/build-and-deploy-alpha-release.yml
+++ b/.github/workflows/build-and-deploy-alpha-release.yml
@@ -35,10 +35,19 @@ jobs:
       - name: Execute Unit Tests
         run: bash ./gradlew testReleaseUnitTest --stacktrace
 
-      - name: Display Unit Tests Result
-        uses: dorny/test-reporter@v1
-        if: success() || failure()
-        with:
-          name: Unit Tests
-          path: app/build/test-results/testReleaseUnitTest/jest-*.xml
-          reporter: jest-junit
+      #      - name: Display Unit Tests Result
+      #        uses: dorny/test-reporter@v1
+      #        if: success() || failure()
+      #        with:
+      #          name: Unit Tests
+      #          path: app/build/test-results/testReleaseUnitTest/jest-*.xml
+      #          reporter: jest-junit
+
+      - name: Build Universal APK (release)
+        id: buildAPKRelease
+        run: |
+          bash ./gradlew packageReleaseUniversalApk --stacktrace
+          #env:
+          #BRANCH_TYPE: ${{ env.BRANCH_TYPE }}
+          #STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
+        #KEY_PASSWORD_RELEASE: ${{ secrets.KEY_PASSWORD_RELEASE }}
